AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
    db-user

    Sample SAM Template for db-people

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 20

Resources:
    PostUserFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: postUser/
            Handler: app.lambdaHandler
            Runtime: nodejs10.x
            Events:
                PostUser:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /user
                        Method: post
    GetUserFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: getUser/
            Handler: app.lambdaHandler
            Runtime: nodejs10.x
            Events:
                PostUser:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /user
                        Method: get

Outputs:
    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    PostUserApi:
        Description: "API Gateway endpoint URL for Prod stage for Hello World function"
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
    PostUserFunction:
        Description: "Hello World Lambda Function ARN"
        Value: !GetAtt PostUserFunction.Arn
    PostUserFunctionIamRole:
        Description: "Implicit IAM Role created for Hello World function"
        Value: !GetAtt PostUserFunctionRole.Arn
    GetUserApi:
        Description: "API Gateway endpoint URL for Prod stage for Hello World function"
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
    GetUserFunction:
        Description: "Hello World Lambda Function ARN"
        Value: !GetAtt GetUserFunction.Arn
    GetUserFunctionIamRole:
        Description: "Implicit IAM Role created for Hello World function"
        Value: !GetAtt GetUserFunctionRole.Arn
